set_smarthome_mode:
  description: Set system into a given smarthome mode.
  fields:
    system: {description: System identifcation to send command to., example: "12345"}
    mode: {description: "Mode to select. Can be DEFAULT_OPERATION, AWAY_FROM_HOME or VACATION", example: "DEFAULT_OPERATION"}
